server.port=${PORT:10000}
server.address=0.0.0.0
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=30000
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true