server.port=${PORT:10000}
server.address=0.0.0.0
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=30000